// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

declare var exports: any;
const __config = new pulumi.Config("planetscale");

/**
 * Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_ID`. Mutually exclusive with <span pulumi-lang-nodejs="`serviceTokenId`" pulumi-lang-dotnet="`ServiceTokenId`" pulumi-lang-go="`serviceTokenId`" pulumi-lang-python="`service_token_id`" pulumi-lang-yaml="`serviceTokenId`" pulumi-lang-java="`serviceTokenId`">`service_token_id`</span> and <span pulumi-lang-nodejs="`serviceToken`" pulumi-lang-dotnet="`ServiceToken`" pulumi-lang-go="`serviceToken`" pulumi-lang-python="`service_token`" pulumi-lang-yaml="`serviceToken`" pulumi-lang-java="`serviceToken`">`service_token`</span>.
 */
export declare const accessToken: string | undefined;
Object.defineProperty(exports, "accessToken", {
  get() {
    return __config.get("accessToken");
  },
  enumerable: true,
});

/**
 * If set, points the API client to a different endpoint than `https://api.planetscale.com/v1`.
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
  get() {
    return __config.get("endpoint");
  },
  enumerable: true,
});

/**
 * Value of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>.
 */
export declare const serviceToken: string | undefined;
Object.defineProperty(exports, "serviceToken", {
  get() {
    return __config.get("serviceToken");
  },
  enumerable: true,
});

/**
 * ID of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_ID`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>.
 */
export declare const serviceTokenId: string | undefined;
Object.defineProperty(exports, "serviceTokenId", {
  get() {
    return __config.get("serviceTokenId");
  },
  enumerable: true,
});

/**
 * Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>. (Deprecated, use <span pulumi-lang-nodejs="`serviceTokenId`" pulumi-lang-dotnet="`ServiceTokenId`" pulumi-lang-go="`serviceTokenId`" pulumi-lang-python="`service_token_id`" pulumi-lang-yaml="`serviceTokenId`" pulumi-lang-java="`serviceTokenId`">`service_token_id`</span> instead)
 */
export declare const serviceTokenName: string | undefined;
Object.defineProperty(exports, "serviceTokenName", {
  get() {
    return __config.get("serviceTokenName");
  },
  enumerable: true,
});
