// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Backup extends pulumi.CustomResource {
  /**
   * Get an existing Backup resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: BackupState,
    opts?: pulumi.CustomResourceOptions,
  ): Backup {
    return new Backup(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = "planetscale:index/backup:Backup";

  /**
   * Returns true if the given object is an instance of Backup.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Backup {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj.__pulumiType === Backup.__pulumiType;
  }

  /**
   * .
   */
  declare public readonly /*out*/ actor: pulumi.Output<outputs.BackupActor>;
  /**
   * The policy used by the backup.
   */
  declare public readonly /*out*/ backupPolicy: pulumi.Output<outputs.BackupBackupPolicy>;
  /**
   * The branch being backed up.
   */
  declare public readonly branch: pulumi.Output<string>;
  /**
   * When the backup was created.
   */
  declare public readonly /*out*/ createdAt: pulumi.Output<string>;
  /**
   * The database to which the branch being backed up belongs to.
   */
  declare public readonly database: pulumi.Output<string>;
  /**
   * The estimated storage cost of the backup.
   */
  declare public readonly /*out*/ estimatedStorageCost: pulumi.Output<number>;
  /**
   * The name of the backup.
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * The organization in which the database branch being backed up belongs to.
   */
  declare public readonly organization: pulumi.Output<string>;
  /**
   * Whether or not the backup policy is required.
   */
  declare public readonly /*out*/ required: pulumi.Output<boolean>;
  /**
   * Branches that have been restored with this backup.
   */
  declare public readonly /*out*/ restoredBranches: pulumi.Output<string[]>;
  /**
   * The unit for the retention period of the backup policy.
   */
  declare public readonly retentionUnit: pulumi.Output<string>;
  /**
   * A number value for the retention period of the backup policy.
   */
  declare public readonly retentionValue: pulumi.Output<number>;
  /**
   * The size of the backup.
   */
  declare public readonly /*out*/ size: pulumi.Output<number>;
  /**
   * The current state of the backup.
   */
  declare public readonly /*out*/ state: pulumi.Output<string>;
  /**
   * When the backup was last updated.
   */
  declare public readonly /*out*/ updatedAt: pulumi.Output<string>;

  /**
   * Create a Backup resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: BackupArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: BackupArgs | BackupState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as BackupState | undefined;
      resourceInputs.actor = state?.actor;
      resourceInputs.backupPolicy = state?.backupPolicy;
      resourceInputs.branch = state?.branch;
      resourceInputs.createdAt = state?.createdAt;
      resourceInputs.database = state?.database;
      resourceInputs.estimatedStorageCost = state?.estimatedStorageCost;
      resourceInputs.name = state?.name;
      resourceInputs.organization = state?.organization;
      resourceInputs.required = state?.required;
      resourceInputs.restoredBranches = state?.restoredBranches;
      resourceInputs.retentionUnit = state?.retentionUnit;
      resourceInputs.retentionValue = state?.retentionValue;
      resourceInputs.size = state?.size;
      resourceInputs.state = state?.state;
      resourceInputs.updatedAt = state?.updatedAt;
    } else {
      const args = argsOrState as BackupArgs | undefined;
      if (args?.branch === undefined && !opts.urn) {
        throw new Error("Missing required property 'branch'");
      }
      if (args?.database === undefined && !opts.urn) {
        throw new Error("Missing required property 'database'");
      }
      if (args?.organization === undefined && !opts.urn) {
        throw new Error("Missing required property 'organization'");
      }
      if (args?.retentionUnit === undefined && !opts.urn) {
        throw new Error("Missing required property 'retentionUnit'");
      }
      if (args?.retentionValue === undefined && !opts.urn) {
        throw new Error("Missing required property 'retentionValue'");
      }
      resourceInputs.branch = args?.branch;
      resourceInputs.database = args?.database;
      resourceInputs.name = args?.name;
      resourceInputs.organization = args?.organization;
      resourceInputs.retentionUnit = args?.retentionUnit;
      resourceInputs.retentionValue = args?.retentionValue;
      resourceInputs.actor = undefined /*out*/;
      resourceInputs.backupPolicy = undefined /*out*/;
      resourceInputs.createdAt = undefined /*out*/;
      resourceInputs.estimatedStorageCost = undefined /*out*/;
      resourceInputs.required = undefined /*out*/;
      resourceInputs.restoredBranches = undefined /*out*/;
      resourceInputs.size = undefined /*out*/;
      resourceInputs.state = undefined /*out*/;
      resourceInputs.updatedAt = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      Backup.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Backup resources.
 */
export interface BackupState {
  /**
   * .
   */
  actor?: pulumi.Input<inputs.BackupActor>;
  /**
   * The policy used by the backup.
   */
  backupPolicy?: pulumi.Input<inputs.BackupBackupPolicy>;
  /**
   * The branch being backed up.
   */
  branch?: pulumi.Input<string>;
  /**
   * When the backup was created.
   */
  createdAt?: pulumi.Input<string>;
  /**
   * The database to which the branch being backed up belongs to.
   */
  database?: pulumi.Input<string>;
  /**
   * The estimated storage cost of the backup.
   */
  estimatedStorageCost?: pulumi.Input<number>;
  /**
   * The name of the backup.
   */
  name?: pulumi.Input<string>;
  /**
   * The organization in which the database branch being backed up belongs to.
   */
  organization?: pulumi.Input<string>;
  /**
   * Whether or not the backup policy is required.
   */
  required?: pulumi.Input<boolean>;
  /**
   * Branches that have been restored with this backup.
   */
  restoredBranches?: pulumi.Input<pulumi.Input<string>[]>;
  /**
   * The unit for the retention period of the backup policy.
   */
  retentionUnit?: pulumi.Input<string>;
  /**
   * A number value for the retention period of the backup policy.
   */
  retentionValue?: pulumi.Input<number>;
  /**
   * The size of the backup.
   */
  size?: pulumi.Input<number>;
  /**
   * The current state of the backup.
   */
  state?: pulumi.Input<string>;
  /**
   * When the backup was last updated.
   */
  updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Backup resource.
 */
export interface BackupArgs {
  /**
   * The branch being backed up.
   */
  branch: pulumi.Input<string>;
  /**
   * The database to which the branch being backed up belongs to.
   */
  database: pulumi.Input<string>;
  /**
   * The name of the backup.
   */
  name?: pulumi.Input<string>;
  /**
   * The organization in which the database branch being backed up belongs to.
   */
  organization: pulumi.Input<string>;
  /**
   * The unit for the retention period of the backup policy.
   */
  retentionUnit: pulumi.Input<string>;
  /**
   * A number value for the retention period of the backup policy.
   */
  retentionValue: pulumi.Input<number>;
}
