// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Branch extends pulumi.CustomResource {
  /**
   * Get an existing Branch resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: BranchState,
    opts?: pulumi.CustomResourceOptions,
  ): Branch {
    return new Branch(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = "planetscale:index/branch:Branch";

  /**
   * Returns true if the given object is an instance of Branch.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Branch {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj.__pulumiType === Branch.__pulumiType;
  }

  /**
   * The actor who created this branch.
   */
  declare public readonly /*out*/ actor: pulumi.Output<outputs.BranchActor>;
  /**
   * When the branch was created.
   */
  declare public readonly /*out*/ createdAt: pulumi.Output<string>;
  /**
   * The database this branch belongs to.
   */
  declare public readonly database: pulumi.Output<string>;
  /**
   * Planetscale app URL for the branch.
   */
  declare public readonly /*out*/ htmlUrl: pulumi.Output<string>;
  /**
   * The MySQL address for the branch.
   */
  declare public readonly /*out*/ mysqlAddress: pulumi.Output<string>;
  /**
   * The address of the MySQL provider for the branch.
   */
  declare public readonly /*out*/ mysqlEdgeAddress: pulumi.Output<string>;
  /**
   * The name of the branch.
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * The organization this branch belongs to.
   */
  declare public readonly organization: pulumi.Output<string>;
  /**
   * The name of the parent branch from which the branch was created.
   */
  declare public readonly parentBranch: pulumi.Output<string>;
  /**
   * Whether or not the branch is a production branch.
   */
  declare public readonly production: pulumi.Output<boolean>;
  /**
   * Whether or not the branch is ready to serve queries.
   */
  declare public readonly /*out*/ ready: pulumi.Output<boolean>;
  /**
   * The region in which this branch lives.
   */
  declare public readonly /*out*/ region: pulumi.Output<outputs.BranchRegion>;
  /**
   * When a user last marked a backup restore checklist as completed.
   */
  declare public readonly /*out*/ restoreChecklistCompletedAt: pulumi.Output<string>;
  /**
   * todo
   */
  declare public readonly /*out*/ restoredFromBranch: pulumi.Output<outputs.BranchRestoredFromBranch>;
  /**
   * When the schema for the branch was last updated.
   */
  declare public readonly /*out*/ schemaLastUpdatedAt: pulumi.Output<string>;
  /**
   * Seed data using the Data Branching® feature. Valid value is <span pulumi-lang-nodejs="`lastSuccessfulBackup`" pulumi-lang-dotnet="`LastSuccessfulBackup`" pulumi-lang-go="`lastSuccessfulBackup`" pulumi-lang-python="`last_successful_backup`" pulumi-lang-yaml="`lastSuccessfulBackup`" pulumi-lang-java="`lastSuccessfulBackup`">`last_successful_backup`</span>
   */
  declare public readonly seedData: pulumi.Output<string | undefined>;
  /**
   * The number of shards in the branch.
   */
  declare public readonly /*out*/ shardCount: pulumi.Output<number>;
  /**
   * Whether or not the branch is sharded.
   */
  declare public readonly /*out*/ sharded: pulumi.Output<boolean>;
  /**
   * When the branch was last updated.
   */
  declare public readonly /*out*/ updatedAt: pulumi.Output<string>;

  /**
   * Create a Branch resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: BranchArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: BranchArgs | BranchState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as BranchState | undefined;
      resourceInputs.actor = state?.actor;
      resourceInputs.createdAt = state?.createdAt;
      resourceInputs.database = state?.database;
      resourceInputs.htmlUrl = state?.htmlUrl;
      resourceInputs.mysqlAddress = state?.mysqlAddress;
      resourceInputs.mysqlEdgeAddress = state?.mysqlEdgeAddress;
      resourceInputs.name = state?.name;
      resourceInputs.organization = state?.organization;
      resourceInputs.parentBranch = state?.parentBranch;
      resourceInputs.production = state?.production;
      resourceInputs.ready = state?.ready;
      resourceInputs.region = state?.region;
      resourceInputs.restoreChecklistCompletedAt = state?.restoreChecklistCompletedAt;
      resourceInputs.restoredFromBranch = state?.restoredFromBranch;
      resourceInputs.schemaLastUpdatedAt = state?.schemaLastUpdatedAt;
      resourceInputs.seedData = state?.seedData;
      resourceInputs.shardCount = state?.shardCount;
      resourceInputs.sharded = state?.sharded;
      resourceInputs.updatedAt = state?.updatedAt;
    } else {
      const args = argsOrState as BranchArgs | undefined;
      if (args?.database === undefined && !opts.urn) {
        throw new Error("Missing required property 'database'");
      }
      if (args?.organization === undefined && !opts.urn) {
        throw new Error("Missing required property 'organization'");
      }
      if (args?.parentBranch === undefined && !opts.urn) {
        throw new Error("Missing required property 'parentBranch'");
      }
      resourceInputs.database = args?.database;
      resourceInputs.name = args?.name;
      resourceInputs.organization = args?.organization;
      resourceInputs.parentBranch = args?.parentBranch;
      resourceInputs.production = args?.production;
      resourceInputs.seedData = args?.seedData;
      resourceInputs.actor = undefined /*out*/;
      resourceInputs.createdAt = undefined /*out*/;
      resourceInputs.htmlUrl = undefined /*out*/;
      resourceInputs.mysqlAddress = undefined /*out*/;
      resourceInputs.mysqlEdgeAddress = undefined /*out*/;
      resourceInputs.ready = undefined /*out*/;
      resourceInputs.region = undefined /*out*/;
      resourceInputs.restoreChecklistCompletedAt = undefined /*out*/;
      resourceInputs.restoredFromBranch = undefined /*out*/;
      resourceInputs.schemaLastUpdatedAt = undefined /*out*/;
      resourceInputs.shardCount = undefined /*out*/;
      resourceInputs.sharded = undefined /*out*/;
      resourceInputs.updatedAt = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      Branch.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Branch resources.
 */
export interface BranchState {
  /**
   * The actor who created this branch.
   */
  actor?: pulumi.Input<inputs.BranchActor>;
  /**
   * When the branch was created.
   */
  createdAt?: pulumi.Input<string>;
  /**
   * The database this branch belongs to.
   */
  database?: pulumi.Input<string>;
  /**
   * Planetscale app URL for the branch.
   */
  htmlUrl?: pulumi.Input<string>;
  /**
   * The MySQL address for the branch.
   */
  mysqlAddress?: pulumi.Input<string>;
  /**
   * The address of the MySQL provider for the branch.
   */
  mysqlEdgeAddress?: pulumi.Input<string>;
  /**
   * The name of the branch.
   */
  name?: pulumi.Input<string>;
  /**
   * The organization this branch belongs to.
   */
  organization?: pulumi.Input<string>;
  /**
   * The name of the parent branch from which the branch was created.
   */
  parentBranch?: pulumi.Input<string>;
  /**
   * Whether or not the branch is a production branch.
   */
  production?: pulumi.Input<boolean>;
  /**
   * Whether or not the branch is ready to serve queries.
   */
  ready?: pulumi.Input<boolean>;
  /**
   * The region in which this branch lives.
   */
  region?: pulumi.Input<inputs.BranchRegion>;
  /**
   * When a user last marked a backup restore checklist as completed.
   */
  restoreChecklistCompletedAt?: pulumi.Input<string>;
  /**
   * todo
   */
  restoredFromBranch?: pulumi.Input<inputs.BranchRestoredFromBranch>;
  /**
   * When the schema for the branch was last updated.
   */
  schemaLastUpdatedAt?: pulumi.Input<string>;
  /**
   * Seed data using the Data Branching® feature. Valid value is <span pulumi-lang-nodejs="`lastSuccessfulBackup`" pulumi-lang-dotnet="`LastSuccessfulBackup`" pulumi-lang-go="`lastSuccessfulBackup`" pulumi-lang-python="`last_successful_backup`" pulumi-lang-yaml="`lastSuccessfulBackup`" pulumi-lang-java="`lastSuccessfulBackup`">`last_successful_backup`</span>
   */
  seedData?: pulumi.Input<string>;
  /**
   * The number of shards in the branch.
   */
  shardCount?: pulumi.Input<number>;
  /**
   * Whether or not the branch is sharded.
   */
  sharded?: pulumi.Input<boolean>;
  /**
   * When the branch was last updated.
   */
  updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Branch resource.
 */
export interface BranchArgs {
  /**
   * The database this branch belongs to.
   */
  database: pulumi.Input<string>;
  /**
   * The name of the branch.
   */
  name?: pulumi.Input<string>;
  /**
   * The organization this branch belongs to.
   */
  organization: pulumi.Input<string>;
  /**
   * The name of the parent branch from which the branch was created.
   */
  parentBranch: pulumi.Input<string>;
  /**
   * Whether or not the branch is a production branch.
   */
  production?: pulumi.Input<boolean>;
  /**
   * Seed data using the Data Branching® feature. Valid value is <span pulumi-lang-nodejs="`lastSuccessfulBackup`" pulumi-lang-dotnet="`LastSuccessfulBackup`" pulumi-lang-go="`lastSuccessfulBackup`" pulumi-lang-python="`last_successful_backup`" pulumi-lang-yaml="`lastSuccessfulBackup`" pulumi-lang-java="`lastSuccessfulBackup`">`last_successful_backup`</span>
   */
  seedData?: pulumi.Input<string>;
}
