// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class BranchSafeMigrations extends pulumi.CustomResource {
  /**
   * Get an existing BranchSafeMigrations resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: BranchSafeMigrationsState,
    opts?: pulumi.CustomResourceOptions,
  ): BranchSafeMigrations {
    return new BranchSafeMigrations(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType =
    "planetscale:index/branchSafeMigrations:BranchSafeMigrations";

  /**
   * Returns true if the given object is an instance of BranchSafeMigrations.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is BranchSafeMigrations {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj.__pulumiType === BranchSafeMigrations.__pulumiType;
  }

  /**
   * The name of the branch to configure safe migrations on..
   */
  declare public readonly branch: pulumi.Output<string>;
  /**
   * The database this branch belongs to.
   */
  declare public readonly database: pulumi.Output<string>;
  /**
   * Whether safe migrations are enabled for this branch.
   */
  declare public readonly enabled: pulumi.Output<boolean>;
  /**
   * The organization this branch belongs to.
   */
  declare public readonly organization: pulumi.Output<string>;

  /**
   * Create a BranchSafeMigrations resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: BranchSafeMigrationsArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: BranchSafeMigrationsArgs | BranchSafeMigrationsState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as BranchSafeMigrationsState | undefined;
      resourceInputs.branch = state?.branch;
      resourceInputs.database = state?.database;
      resourceInputs.enabled = state?.enabled;
      resourceInputs.organization = state?.organization;
    } else {
      const args = argsOrState as BranchSafeMigrationsArgs | undefined;
      if (args?.branch === undefined && !opts.urn) {
        throw new Error("Missing required property 'branch'");
      }
      if (args?.database === undefined && !opts.urn) {
        throw new Error("Missing required property 'database'");
      }
      if (args?.enabled === undefined && !opts.urn) {
        throw new Error("Missing required property 'enabled'");
      }
      if (args?.organization === undefined && !opts.urn) {
        throw new Error("Missing required property 'organization'");
      }
      resourceInputs.branch = args?.branch;
      resourceInputs.database = args?.database;
      resourceInputs.enabled = args?.enabled;
      resourceInputs.organization = args?.organization;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      BranchSafeMigrations.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering BranchSafeMigrations resources.
 */
export interface BranchSafeMigrationsState {
  /**
   * The name of the branch to configure safe migrations on..
   */
  branch?: pulumi.Input<string>;
  /**
   * The database this branch belongs to.
   */
  database?: pulumi.Input<string>;
  /**
   * Whether safe migrations are enabled for this branch.
   */
  enabled?: pulumi.Input<boolean>;
  /**
   * The organization this branch belongs to.
   */
  organization?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a BranchSafeMigrations resource.
 */
export interface BranchSafeMigrationsArgs {
  /**
   * The name of the branch to configure safe migrations on..
   */
  branch: pulumi.Input<string>;
  /**
   * The database this branch belongs to.
   */
  database: pulumi.Input<string>;
  /**
   * Whether safe migrations are enabled for this branch.
   */
  enabled: pulumi.Input<boolean>;
  /**
   * The organization this branch belongs to.
   */
  organization: pulumi.Input<string>;
}
