// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Database extends pulumi.CustomResource {
  /**
   * Get an existing Database resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: DatabaseState,
    opts?: pulumi.CustomResourceOptions,
  ): Database {
    return new Database(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = "planetscale:index/database:Database";

  /**
   * Returns true if the given object is an instance of Database.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Database {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj.__pulumiType === Database.__pulumiType;
  }

  /**
   * Whether seeding branches with data is enabled for all branches.
   */
  declare public readonly allowDataBranching: pulumi.Output<boolean>;
  /**
   * If the database has reached its backup restored branch limit.
   */
  declare public readonly /*out*/ atBackupRestoreBranchesLimit: pulumi.Output<boolean>;
  /**
   * If the database has reached its development branch limit.
   */
  declare public readonly /*out*/ atDevelopmentBranchLimit: pulumi.Output<boolean>;
  /**
   * Whether to automatically manage migrations during deploy requests. If true, <span pulumi-lang-nodejs="`migrationTableName`" pulumi-lang-dotnet="`MigrationTableName`" pulumi-lang-go="`migrationTableName`" pulumi-lang-python="`migration_table_name`" pulumi-lang-yaml="`migrationTableName`" pulumi-lang-java="`migrationTableName`">`migration_table_name`</span> and <span pulumi-lang-nodejs="`migrationFramework`" pulumi-lang-dotnet="`MigrationFramework`" pulumi-lang-go="`migrationFramework`" pulumi-lang-python="`migration_framework`" pulumi-lang-yaml="`migrationFramework`" pulumi-lang-java="`migrationFramework`">`migration_framework`</span> must be set.
   */
  declare public readonly automaticMigrations: pulumi.Output<boolean>;
  /**
   * The total number of database branches.
   */
  declare public readonly /*out*/ branchesCount: pulumi.Output<number>;
  /**
   * The URL to retrieve this database's branches via the API.
   */
  declare public readonly /*out*/ branchesUrl: pulumi.Output<string>;
  /**
   * The default plan size of the database's branches.
   */
  declare public readonly clusterSize: pulumi.Output<string>;
  /**
   * When the database was created.
   */
  declare public readonly /*out*/ createdAt: pulumi.Output<string>;
  /**
   * If the database was created from an import, describes the import process.
   */
  declare public readonly /*out*/ dataImport: pulumi.Output<outputs.DatabaseDataImport>;
  /**
   * The default branch for the database.
   */
  declare public readonly defaultBranch: pulumi.Output<string>;
  /**
   * Number of read only regions in the default branch.
   */
  declare public readonly /*out*/ defaultBranchReadOnlyRegionsCount: pulumi.Output<number>;
  /**
   * Number of shards in the default branch.
   */
  declare public readonly /*out*/ defaultBranchShardCount: pulumi.Output<number>;
  /**
   * Number of tables in the default branch schema.
   */
  declare public readonly /*out*/ defaultBranchTableCount: pulumi.Output<number>;
  /**
   * The total number of database development branches.
   */
  declare public readonly /*out*/ developmentBranchesCount: pulumi.Output<number>;
  /**
   * The total number of database development branches.
   */
  declare public readonly /*out*/ htmlUrl: pulumi.Output<string>;
  /**
   * The URL to see this database's branches in the web UI.
   */
  declare public readonly insightsRawQueries: pulumi.Output<boolean>;
  /**
   * The total number of ongoing issues within a database.
   */
  declare public readonly /*out*/ issuesCount: pulumi.Output<number>;
  /**
   * Framework used for applying migrations.
   */
  declare public readonly migrationFramework: pulumi.Output<string>;
  /**
   * Table name to use for copying schema migration data.
   */
  declare public readonly migrationTableName: pulumi.Output<string>;
  /**
   * If the database requires multiple admins for deletion.
   */
  declare public readonly /*out*/ multipleAdminsRequiredForDeletion: pulumi.Output<boolean>;
  /**
   * The name of this database.
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * The organization this database belongs to.
   */
  declare public readonly organization: pulumi.Output<string>;
  /**
   * The database plan.
   */
  declare public readonly /*out*/ plan: pulumi.Output<string>;
  /**
   * Whether web console is enabled for production branches.
   */
  declare public readonly productionBranchWebConsole: pulumi.Output<boolean>;
  /**
   * The total number of database production branches.
   */
  declare public readonly /*out*/ productionBranchesCount: pulumi.Output<number>;
  /**
   * If the database is ready to be used.
   */
  declare public readonly /*out*/ ready: pulumi.Output<boolean>;
  /**
   * The region the database lives in.
   */
  declare public readonly region: pulumi.Output<string>;
  /**
   * Whether an approval is required to deploy schema changes to this database.
   */
  declare public readonly requireApprovalForDeploy: pulumi.Output<boolean>;
  /**
   * Whether to restrict branch creation to one region.
   */
  declare public readonly restrictBranchRegion: pulumi.Output<boolean>;
  /**
   * When the default branch schema was last changed.
   */
  declare public readonly /*out*/ schemaLastUpdatedAt: pulumi.Output<string>;
  /**
   * If the database is sharded.
   */
  declare public readonly /*out*/ sharded: pulumi.Output<boolean>;
  /**
   * State of the database.
   */
  declare public readonly /*out*/ state: pulumi.Output<string>;
  /**
   * When the database was last updated.
   */
  declare public readonly /*out*/ updatedAt: pulumi.Output<string>;
  /**
   * The URL to the database API endpoint.
   */
  declare public readonly /*out*/ url: pulumi.Output<string>;

  /**
   * Create a Database resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: DatabaseArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: DatabaseArgs | DatabaseState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as DatabaseState | undefined;
      resourceInputs.allowDataBranching = state?.allowDataBranching;
      resourceInputs.atBackupRestoreBranchesLimit = state?.atBackupRestoreBranchesLimit;
      resourceInputs.atDevelopmentBranchLimit = state?.atDevelopmentBranchLimit;
      resourceInputs.automaticMigrations = state?.automaticMigrations;
      resourceInputs.branchesCount = state?.branchesCount;
      resourceInputs.branchesUrl = state?.branchesUrl;
      resourceInputs.clusterSize = state?.clusterSize;
      resourceInputs.createdAt = state?.createdAt;
      resourceInputs.dataImport = state?.dataImport;
      resourceInputs.defaultBranch = state?.defaultBranch;
      resourceInputs.defaultBranchReadOnlyRegionsCount = state?.defaultBranchReadOnlyRegionsCount;
      resourceInputs.defaultBranchShardCount = state?.defaultBranchShardCount;
      resourceInputs.defaultBranchTableCount = state?.defaultBranchTableCount;
      resourceInputs.developmentBranchesCount = state?.developmentBranchesCount;
      resourceInputs.htmlUrl = state?.htmlUrl;
      resourceInputs.insightsRawQueries = state?.insightsRawQueries;
      resourceInputs.issuesCount = state?.issuesCount;
      resourceInputs.migrationFramework = state?.migrationFramework;
      resourceInputs.migrationTableName = state?.migrationTableName;
      resourceInputs.multipleAdminsRequiredForDeletion = state?.multipleAdminsRequiredForDeletion;
      resourceInputs.name = state?.name;
      resourceInputs.organization = state?.organization;
      resourceInputs.plan = state?.plan;
      resourceInputs.productionBranchWebConsole = state?.productionBranchWebConsole;
      resourceInputs.productionBranchesCount = state?.productionBranchesCount;
      resourceInputs.ready = state?.ready;
      resourceInputs.region = state?.region;
      resourceInputs.requireApprovalForDeploy = state?.requireApprovalForDeploy;
      resourceInputs.restrictBranchRegion = state?.restrictBranchRegion;
      resourceInputs.schemaLastUpdatedAt = state?.schemaLastUpdatedAt;
      resourceInputs.sharded = state?.sharded;
      resourceInputs.state = state?.state;
      resourceInputs.updatedAt = state?.updatedAt;
      resourceInputs.url = state?.url;
    } else {
      const args = argsOrState as DatabaseArgs | undefined;
      if (args?.clusterSize === undefined && !opts.urn) {
        throw new Error("Missing required property 'clusterSize'");
      }
      if (args?.organization === undefined && !opts.urn) {
        throw new Error("Missing required property 'organization'");
      }
      resourceInputs.allowDataBranching = args?.allowDataBranching;
      resourceInputs.automaticMigrations = args?.automaticMigrations;
      resourceInputs.clusterSize = args?.clusterSize;
      resourceInputs.defaultBranch = args?.defaultBranch;
      resourceInputs.insightsRawQueries = args?.insightsRawQueries;
      resourceInputs.migrationFramework = args?.migrationFramework;
      resourceInputs.migrationTableName = args?.migrationTableName;
      resourceInputs.name = args?.name;
      resourceInputs.organization = args?.organization;
      resourceInputs.productionBranchWebConsole = args?.productionBranchWebConsole;
      resourceInputs.region = args?.region;
      resourceInputs.requireApprovalForDeploy = args?.requireApprovalForDeploy;
      resourceInputs.restrictBranchRegion = args?.restrictBranchRegion;
      resourceInputs.atBackupRestoreBranchesLimit = undefined /*out*/;
      resourceInputs.atDevelopmentBranchLimit = undefined /*out*/;
      resourceInputs.branchesCount = undefined /*out*/;
      resourceInputs.branchesUrl = undefined /*out*/;
      resourceInputs.createdAt = undefined /*out*/;
      resourceInputs.dataImport = undefined /*out*/;
      resourceInputs.defaultBranchReadOnlyRegionsCount = undefined /*out*/;
      resourceInputs.defaultBranchShardCount = undefined /*out*/;
      resourceInputs.defaultBranchTableCount = undefined /*out*/;
      resourceInputs.developmentBranchesCount = undefined /*out*/;
      resourceInputs.htmlUrl = undefined /*out*/;
      resourceInputs.issuesCount = undefined /*out*/;
      resourceInputs.multipleAdminsRequiredForDeletion = undefined /*out*/;
      resourceInputs.plan = undefined /*out*/;
      resourceInputs.productionBranchesCount = undefined /*out*/;
      resourceInputs.ready = undefined /*out*/;
      resourceInputs.schemaLastUpdatedAt = undefined /*out*/;
      resourceInputs.sharded = undefined /*out*/;
      resourceInputs.state = undefined /*out*/;
      resourceInputs.updatedAt = undefined /*out*/;
      resourceInputs.url = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      Database.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Database resources.
 */
export interface DatabaseState {
  /**
   * Whether seeding branches with data is enabled for all branches.
   */
  allowDataBranching?: pulumi.Input<boolean>;
  /**
   * If the database has reached its backup restored branch limit.
   */
  atBackupRestoreBranchesLimit?: pulumi.Input<boolean>;
  /**
   * If the database has reached its development branch limit.
   */
  atDevelopmentBranchLimit?: pulumi.Input<boolean>;
  /**
   * Whether to automatically manage migrations during deploy requests. If true, <span pulumi-lang-nodejs="`migrationTableName`" pulumi-lang-dotnet="`MigrationTableName`" pulumi-lang-go="`migrationTableName`" pulumi-lang-python="`migration_table_name`" pulumi-lang-yaml="`migrationTableName`" pulumi-lang-java="`migrationTableName`">`migration_table_name`</span> and <span pulumi-lang-nodejs="`migrationFramework`" pulumi-lang-dotnet="`MigrationFramework`" pulumi-lang-go="`migrationFramework`" pulumi-lang-python="`migration_framework`" pulumi-lang-yaml="`migrationFramework`" pulumi-lang-java="`migrationFramework`">`migration_framework`</span> must be set.
   */
  automaticMigrations?: pulumi.Input<boolean>;
  /**
   * The total number of database branches.
   */
  branchesCount?: pulumi.Input<number>;
  /**
   * The URL to retrieve this database's branches via the API.
   */
  branchesUrl?: pulumi.Input<string>;
  /**
   * The default plan size of the database's branches.
   */
  clusterSize?: pulumi.Input<string>;
  /**
   * When the database was created.
   */
  createdAt?: pulumi.Input<string>;
  /**
   * If the database was created from an import, describes the import process.
   */
  dataImport?: pulumi.Input<inputs.DatabaseDataImport>;
  /**
   * The default branch for the database.
   */
  defaultBranch?: pulumi.Input<string>;
  /**
   * Number of read only regions in the default branch.
   */
  defaultBranchReadOnlyRegionsCount?: pulumi.Input<number>;
  /**
   * Number of shards in the default branch.
   */
  defaultBranchShardCount?: pulumi.Input<number>;
  /**
   * Number of tables in the default branch schema.
   */
  defaultBranchTableCount?: pulumi.Input<number>;
  /**
   * The total number of database development branches.
   */
  developmentBranchesCount?: pulumi.Input<number>;
  /**
   * The total number of database development branches.
   */
  htmlUrl?: pulumi.Input<string>;
  /**
   * The URL to see this database's branches in the web UI.
   */
  insightsRawQueries?: pulumi.Input<boolean>;
  /**
   * The total number of ongoing issues within a database.
   */
  issuesCount?: pulumi.Input<number>;
  /**
   * Framework used for applying migrations.
   */
  migrationFramework?: pulumi.Input<string>;
  /**
   * Table name to use for copying schema migration data.
   */
  migrationTableName?: pulumi.Input<string>;
  /**
   * If the database requires multiple admins for deletion.
   */
  multipleAdminsRequiredForDeletion?: pulumi.Input<boolean>;
  /**
   * The name of this database.
   */
  name?: pulumi.Input<string>;
  /**
   * The organization this database belongs to.
   */
  organization?: pulumi.Input<string>;
  /**
   * The database plan.
   */
  plan?: pulumi.Input<string>;
  /**
   * Whether web console is enabled for production branches.
   */
  productionBranchWebConsole?: pulumi.Input<boolean>;
  /**
   * The total number of database production branches.
   */
  productionBranchesCount?: pulumi.Input<number>;
  /**
   * If the database is ready to be used.
   */
  ready?: pulumi.Input<boolean>;
  /**
   * The region the database lives in.
   */
  region?: pulumi.Input<string>;
  /**
   * Whether an approval is required to deploy schema changes to this database.
   */
  requireApprovalForDeploy?: pulumi.Input<boolean>;
  /**
   * Whether to restrict branch creation to one region.
   */
  restrictBranchRegion?: pulumi.Input<boolean>;
  /**
   * When the default branch schema was last changed.
   */
  schemaLastUpdatedAt?: pulumi.Input<string>;
  /**
   * If the database is sharded.
   */
  sharded?: pulumi.Input<boolean>;
  /**
   * State of the database.
   */
  state?: pulumi.Input<string>;
  /**
   * When the database was last updated.
   */
  updatedAt?: pulumi.Input<string>;
  /**
   * The URL to the database API endpoint.
   */
  url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
  /**
   * Whether seeding branches with data is enabled for all branches.
   */
  allowDataBranching?: pulumi.Input<boolean>;
  /**
   * Whether to automatically manage migrations during deploy requests. If true, <span pulumi-lang-nodejs="`migrationTableName`" pulumi-lang-dotnet="`MigrationTableName`" pulumi-lang-go="`migrationTableName`" pulumi-lang-python="`migration_table_name`" pulumi-lang-yaml="`migrationTableName`" pulumi-lang-java="`migrationTableName`">`migration_table_name`</span> and <span pulumi-lang-nodejs="`migrationFramework`" pulumi-lang-dotnet="`MigrationFramework`" pulumi-lang-go="`migrationFramework`" pulumi-lang-python="`migration_framework`" pulumi-lang-yaml="`migrationFramework`" pulumi-lang-java="`migrationFramework`">`migration_framework`</span> must be set.
   */
  automaticMigrations?: pulumi.Input<boolean>;
  /**
   * The default plan size of the database's branches.
   */
  clusterSize: pulumi.Input<string>;
  /**
   * The default branch for the database.
   */
  defaultBranch?: pulumi.Input<string>;
  /**
   * The URL to see this database's branches in the web UI.
   */
  insightsRawQueries?: pulumi.Input<boolean>;
  /**
   * Framework used for applying migrations.
   */
  migrationFramework?: pulumi.Input<string>;
  /**
   * Table name to use for copying schema migration data.
   */
  migrationTableName?: pulumi.Input<string>;
  /**
   * The name of this database.
   */
  name?: pulumi.Input<string>;
  /**
   * The organization this database belongs to.
   */
  organization: pulumi.Input<string>;
  /**
   * Whether web console is enabled for production branches.
   */
  productionBranchWebConsole?: pulumi.Input<boolean>;
  /**
   * The region the database lives in.
   */
  region?: pulumi.Input<string>;
  /**
   * Whether an approval is required to deploy schema changes to this database.
   */
  requireApprovalForDeploy?: pulumi.Input<boolean>;
  /**
   * Whether to restrict branch creation to one region.
   */
  restrictBranchRegion?: pulumi.Input<boolean>;
}
