// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBranchSchemaLint(
  args: GetBranchSchemaLintArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBranchSchemaLintResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getBranchSchemaLint:getBranchSchemaLint",
    {
      branch: args.branch,
      database: args.database,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchSchemaLint.
 */
export interface GetBranchSchemaLintArgs {
  branch: string;
  database: string;
  organization: string;
}

/**
 * A collection of values returned by getBranchSchemaLint.
 */
export interface GetBranchSchemaLintResult {
  readonly branch: string;
  readonly database: string;
  readonly errors: outputs.GetBranchSchemaLintError[];
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly organization: string;
}
export function getBranchSchemaLintOutput(
  args: GetBranchSchemaLintOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBranchSchemaLintResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getBranchSchemaLint:getBranchSchemaLint",
    {
      branch: args.branch,
      database: args.database,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchSchemaLint.
 */
export interface GetBranchSchemaLintOutputArgs {
  branch: pulumi.Input<string>;
  database: pulumi.Input<string>;
  organization: pulumi.Input<string>;
}
