// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getBranchSafeMigrations(
  args: GetBranchSafeMigrationsArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBranchSafeMigrationsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getBranchSafeMigrations:getBranchSafeMigrations",
    {
      branch: args.branch,
      database: args.database,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchSafeMigrations.
 */
export interface GetBranchSafeMigrationsArgs {
  branch: string;
  database: string;
  organization: string;
}

/**
 * A collection of values returned by getBranchSafeMigrations.
 */
export interface GetBranchSafeMigrationsResult {
  readonly branch: string;
  readonly database: string;
  readonly enabled: boolean;
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly organization: string;
}
export function getBranchSafeMigrationsOutput(
  args: GetBranchSafeMigrationsOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBranchSafeMigrationsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getBranchSafeMigrations:getBranchSafeMigrations",
    {
      branch: args.branch,
      database: args.database,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchSafeMigrations.
 */
export interface GetBranchSafeMigrationsOutputArgs {
  branch: pulumi.Input<string>;
  database: pulumi.Input<string>;
  organization: pulumi.Input<string>;
}
