// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBackups(
  args: GetBackupsArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBackupsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getBackups:getBackups",
    {
      branch: args.branch,
      database: args.database,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBackups.
 */
export interface GetBackupsArgs {
  branch: string;
  database: string;
  organization: string;
}

/**
 * A collection of values returned by getBackups.
 */
export interface GetBackupsResult {
  readonly backups: outputs.GetBackupsBackup[];
  readonly branch: string;
  readonly database: string;
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly organization: string;
}
export function getBackupsOutput(
  args: GetBackupsOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBackupsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getBackups:getBackups",
    {
      branch: args.branch,
      database: args.database,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBackups.
 */
export interface GetBackupsOutputArgs {
  branch: pulumi.Input<string>;
  database: pulumi.Input<string>;
  organization: pulumi.Input<string>;
}
