// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBackup(
  args: GetBackupArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBackupResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getBackup:getBackup",
    {
      branch: args.branch,
      database: args.database,
      id: args.id,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBackup.
 */
export interface GetBackupArgs {
  branch: string;
  database: string;
  id: string;
  organization: string;
}

/**
 * A collection of values returned by getBackup.
 */
export interface GetBackupResult {
  readonly actor: outputs.GetBackupActor;
  readonly backupPolicy: outputs.GetBackupBackupPolicy;
  readonly branch: string;
  readonly createdAt: string;
  readonly database: string;
  readonly estimatedStorageCost: number;
  readonly id: string;
  readonly name: string;
  readonly organization: string;
  readonly required: boolean;
  readonly restoredBranches: string[];
  readonly size: number;
  readonly state: string;
  readonly updatedAt: string;
}
export function getBackupOutput(
  args: GetBackupOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBackupResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getBackup:getBackup",
    {
      branch: args.branch,
      database: args.database,
      id: args.id,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBackup.
 */
export interface GetBackupOutputArgs {
  branch: pulumi.Input<string>;
  database: pulumi.Input<string>;
  id: pulumi.Input<string>;
  organization: pulumi.Input<string>;
}
