// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBranch(
  args: GetBranchArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBranchResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getBranch:getBranch",
    {
      database: args.database,
      name: args.name,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranch.
 */
export interface GetBranchArgs {
  database: string;
  name: string;
  organization: string;
}

/**
 * A collection of values returned by getBranch.
 */
export interface GetBranchResult {
  readonly accessHostUrl: string;
  readonly actor: outputs.GetBranchActor;
  readonly clusterRateName: string;
  readonly createdAt: string;
  readonly database: string;
  readonly htmlUrl: string;
  readonly id: string;
  readonly initialRestoreId: string;
  readonly mysqlAddress: string;
  readonly mysqlEdgeAddress: string;
  readonly name: string;
  readonly organization: string;
  readonly parentBranch: string;
  readonly production: boolean;
  readonly ready: boolean;
  readonly region: outputs.GetBranchRegion;
  readonly restoreChecklistCompletedAt: string;
  readonly restoredFromBranch: outputs.GetBranchRestoredFromBranch;
  readonly safeMigrations: boolean;
  readonly schemaLastUpdatedAt: string;
  readonly shardCount: number;
  readonly sharded: boolean;
  readonly updatedAt: string;
}
export function getBranchOutput(
  args: GetBranchOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBranchResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getBranch:getBranch",
    {
      database: args.database,
      name: args.name,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranch.
 */
export interface GetBranchOutputArgs {
  database: pulumi.Input<string>;
  name: pulumi.Input<string>;
  organization: pulumi.Input<string>;
}
