// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBranches(
  args: GetBranchesArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBranchesResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getBranches:getBranches",
    {
      database: args.database,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranches.
 */
export interface GetBranchesArgs {
  database: string;
  organization: string;
}

/**
 * A collection of values returned by getBranches.
 */
export interface GetBranchesResult {
  readonly branches: outputs.GetBranchesBranch[];
  readonly database: string;
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly organization: string;
}
export function getBranchesOutput(
  args: GetBranchesOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBranchesResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getBranches:getBranches",
    {
      database: args.database,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranches.
 */
export interface GetBranchesOutputArgs {
  database: pulumi.Input<string>;
  organization: pulumi.Input<string>;
}
