// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDatabases(
  args: GetDatabasesArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetDatabasesResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getDatabases:getDatabases",
    {
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDatabases.
 */
export interface GetDatabasesArgs {
  organization: string;
}

/**
 * A collection of values returned by getDatabases.
 */
export interface GetDatabasesResult {
  readonly databases: outputs.GetDatabasesDatabase[];
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly organization: string;
}
export function getDatabasesOutput(
  args: GetDatabasesOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetDatabasesResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getDatabases:getDatabases",
    {
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDatabases.
 */
export interface GetDatabasesOutputArgs {
  organization: pulumi.Input<string>;
}
