// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDatabase(
  args: GetDatabaseArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetDatabaseResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getDatabase:getDatabase",
    {
      allowDataBranching: args.allowDataBranching,
      automaticMigrations: args.automaticMigrations,
      dataImport: args.dataImport,
      defaultBranch: args.defaultBranch,
      insightsRawQueries: args.insightsRawQueries,
      issuesCount: args.issuesCount,
      migrationFramework: args.migrationFramework,
      migrationTableName: args.migrationTableName,
      multipleAdminsRequiredForDeletion: args.multipleAdminsRequiredForDeletion,
      name: args.name,
      organization: args.organization,
      plan: args.plan,
      productionBranchWebConsole: args.productionBranchWebConsole,
      region: args.region,
      requireApprovalForDeploy: args.requireApprovalForDeploy,
      restrictBranchRegion: args.restrictBranchRegion,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDatabase.
 */
export interface GetDatabaseArgs {
  allowDataBranching?: boolean;
  automaticMigrations?: boolean;
  dataImport?: inputs.GetDatabaseDataImport;
  defaultBranch?: string;
  insightsRawQueries?: boolean;
  issuesCount?: number;
  migrationFramework?: string;
  migrationTableName?: string;
  multipleAdminsRequiredForDeletion?: boolean;
  name: string;
  organization: string;
  plan?: string;
  productionBranchWebConsole?: boolean;
  region?: inputs.GetDatabaseRegion;
  requireApprovalForDeploy?: boolean;
  restrictBranchRegion?: boolean;
}

/**
 * A collection of values returned by getDatabase.
 */
export interface GetDatabaseResult {
  readonly allowDataBranching: boolean;
  readonly atBackupRestoreBranchesLimit: boolean;
  readonly atDevelopmentBranchLimit: boolean;
  readonly automaticMigrations: boolean;
  readonly branchesCount: number;
  readonly branchesUrl: string;
  readonly createdAt: string;
  readonly dataImport?: outputs.GetDatabaseDataImport;
  readonly defaultBranch: string;
  readonly defaultBranchReadOnlyRegionsCount: number;
  readonly defaultBranchShardCount: number;
  readonly defaultBranchTableCount: number;
  readonly developmentBranchesCount: number;
  readonly htmlUrl: string;
  readonly id: string;
  readonly insightsRawQueries: boolean;
  readonly issuesCount: number;
  readonly migrationFramework: string;
  readonly migrationTableName: string;
  readonly multipleAdminsRequiredForDeletion: boolean;
  readonly name: string;
  readonly organization: string;
  readonly plan: string;
  readonly productionBranchWebConsole: boolean;
  readonly productionBranchesCount: number;
  readonly ready: boolean;
  readonly region: outputs.GetDatabaseRegion;
  readonly requireApprovalForDeploy: boolean;
  readonly restrictBranchRegion: boolean;
  readonly schemaLastUpdatedAt: string;
  readonly sharded: boolean;
  readonly state: string;
  readonly updatedAt: string;
  readonly url: string;
}
export function getDatabaseOutput(
  args: GetDatabaseOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetDatabaseResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getDatabase:getDatabase",
    {
      allowDataBranching: args.allowDataBranching,
      automaticMigrations: args.automaticMigrations,
      dataImport: args.dataImport,
      defaultBranch: args.defaultBranch,
      insightsRawQueries: args.insightsRawQueries,
      issuesCount: args.issuesCount,
      migrationFramework: args.migrationFramework,
      migrationTableName: args.migrationTableName,
      multipleAdminsRequiredForDeletion: args.multipleAdminsRequiredForDeletion,
      name: args.name,
      organization: args.organization,
      plan: args.plan,
      productionBranchWebConsole: args.productionBranchWebConsole,
      region: args.region,
      requireApprovalForDeploy: args.requireApprovalForDeploy,
      restrictBranchRegion: args.restrictBranchRegion,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDatabase.
 */
export interface GetDatabaseOutputArgs {
  allowDataBranching?: pulumi.Input<boolean>;
  automaticMigrations?: pulumi.Input<boolean>;
  dataImport?: pulumi.Input<inputs.GetDatabaseDataImportArgs>;
  defaultBranch?: pulumi.Input<string>;
  insightsRawQueries?: pulumi.Input<boolean>;
  issuesCount?: pulumi.Input<number>;
  migrationFramework?: pulumi.Input<string>;
  migrationTableName?: pulumi.Input<string>;
  multipleAdminsRequiredForDeletion?: pulumi.Input<boolean>;
  name: pulumi.Input<string>;
  organization: pulumi.Input<string>;
  plan?: pulumi.Input<string>;
  productionBranchWebConsole?: pulumi.Input<boolean>;
  region?: pulumi.Input<inputs.GetDatabaseRegionArgs>;
  requireApprovalForDeploy?: pulumi.Input<boolean>;
  restrictBranchRegion?: pulumi.Input<boolean>;
}
