// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDatabaseRegions(
  args: GetDatabaseRegionsArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetDatabaseRegionsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getDatabaseRegions:getDatabaseRegions",
    {
      name: args.name,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDatabaseRegions.
 */
export interface GetDatabaseRegionsArgs {
  name: string;
  organization: string;
}

/**
 * A collection of values returned by getDatabaseRegions.
 */
export interface GetDatabaseRegionsResult {
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly name: string;
  readonly organization: string;
  readonly regions: outputs.GetDatabaseRegionsRegion[];
}
export function getDatabaseRegionsOutput(
  args: GetDatabaseRegionsOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetDatabaseRegionsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getDatabaseRegions:getDatabaseRegions",
    {
      name: args.name,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDatabaseRegions.
 */
export interface GetDatabaseRegionsOutputArgs {
  name: pulumi.Input<string>;
  organization: pulumi.Input<string>;
}
