// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDatabaseReadOnlyRegions(
  args: GetDatabaseReadOnlyRegionsArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetDatabaseReadOnlyRegionsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getDatabaseReadOnlyRegions:getDatabaseReadOnlyRegions",
    {
      name: args.name,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDatabaseReadOnlyRegions.
 */
export interface GetDatabaseReadOnlyRegionsArgs {
  name: string;
  organization: string;
}

/**
 * A collection of values returned by getDatabaseReadOnlyRegions.
 */
export interface GetDatabaseReadOnlyRegionsResult {
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly name: string;
  readonly organization: string;
  readonly regions: outputs.GetDatabaseReadOnlyRegionsRegion[];
}
export function getDatabaseReadOnlyRegionsOutput(
  args: GetDatabaseReadOnlyRegionsOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetDatabaseReadOnlyRegionsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getDatabaseReadOnlyRegions:getDatabaseReadOnlyRegions",
    {
      name: args.name,
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDatabaseReadOnlyRegions.
 */
export interface GetDatabaseReadOnlyRegionsOutputArgs {
  name: pulumi.Input<string>;
  organization: pulumi.Input<string>;
}
