// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getOrganizations(opts?: pulumi.InvokeOptions): Promise<GetOrganizationsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getOrganizations:getOrganizations",
    {},
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of values returned by getOrganizations.
 */
export interface GetOrganizationsResult {
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly organizations: outputs.GetOrganizationsOrganization[];
}
export function getOrganizationsOutput(
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetOrganizationsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getOrganizations:getOrganizations",
    {},
    opts,
    utilities.getPackage(),
  );
}
