// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getOrganization(
  args: GetOrganizationArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetOrganizationResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getOrganization:getOrganization",
    {
      name: args.name,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getOrganization.
 */
export interface GetOrganizationArgs {
  name: string;
}

/**
 * A collection of values returned by getOrganization.
 */
export interface GetOrganizationResult {
  readonly billingEmail: string;
  readonly createdAt: string;
  readonly databaseCount: number;
  readonly features: outputs.GetOrganizationFeatures;
  readonly flags: outputs.GetOrganizationFlags;
  readonly hasPastDueInvoices: boolean;
  readonly id: string;
  readonly idpManagedRoles: boolean;
  readonly name: string;
  readonly plan: string;
  readonly singleTenancy: boolean;
  readonly sso: boolean;
  readonly ssoDirectory: boolean;
  readonly ssoPortalUrl: string;
  readonly updatedAt: string;
  readonly validBillingInfo: boolean;
}
export function getOrganizationOutput(
  args: GetOrganizationOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetOrganizationResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getOrganization:getOrganization",
    {
      name: args.name,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getOrganization.
 */
export interface GetOrganizationOutputArgs {
  name: pulumi.Input<string>;
}
