// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getOrganizationRegions(
  args: GetOrganizationRegionsArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetOrganizationRegionsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getOrganizationRegions:getOrganizationRegions",
    {
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getOrganizationRegions.
 */
export interface GetOrganizationRegionsArgs {
  organization: string;
}

/**
 * A collection of values returned by getOrganizationRegions.
 */
export interface GetOrganizationRegionsResult {
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly organization: string;
  readonly regions: outputs.GetOrganizationRegionsRegion[];
}
export function getOrganizationRegionsOutput(
  args: GetOrganizationRegionsOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetOrganizationRegionsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getOrganizationRegions:getOrganizationRegions",
    {
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getOrganizationRegions.
 */
export interface GetOrganizationRegionsOutputArgs {
  organization: pulumi.Input<string>;
}
