// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getOauthApplications(
  args: GetOauthApplicationsArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetOauthApplicationsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getOauthApplications:getOauthApplications",
    {
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getOauthApplications.
 */
export interface GetOauthApplicationsArgs {
  organization: string;
}

/**
 * A collection of values returned by getOauthApplications.
 */
export interface GetOauthApplicationsResult {
  readonly applications: outputs.GetOauthApplicationsApplication[];
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  readonly id: string;
  readonly organization: string;
}
export function getOauthApplicationsOutput(
  args: GetOauthApplicationsOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetOauthApplicationsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getOauthApplications:getOauthApplications",
    {
      organization: args.organization,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getOauthApplications.
 */
export interface GetOauthApplicationsOutputArgs {
  organization: pulumi.Input<string>;
}
