// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPassword(
  args: GetPasswordArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetPasswordResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getPassword:getPassword",
    {
      branch: args.branch,
      database: args.database,
      id: args.id,
      organization: args.organization,
      readOnlyRegionId: args.readOnlyRegionId,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getPassword.
 */
export interface GetPasswordArgs {
  branch: string;
  database: string;
  id: string;
  organization: string;
  readOnlyRegionId?: string;
}

/**
 * A collection of values returned by getPassword.
 */
export interface GetPasswordResult {
  readonly accessHostUrl: string;
  readonly actor: outputs.GetPasswordActor;
  readonly branch: string;
  readonly createdAt: string;
  readonly database: string;
  readonly databaseBranch: outputs.GetPasswordDatabaseBranch;
  readonly deletedAt: string;
  readonly expiresAt: string;
  readonly id: string;
  readonly name: string;
  readonly organization: string;
  readonly readOnlyRegionId?: string;
  readonly region: outputs.GetPasswordRegion;
  readonly renewable: boolean;
  readonly role: string;
  readonly ttlSeconds: number;
  readonly username: string;
}
export function getPasswordOutput(
  args: GetPasswordOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetPasswordResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getPassword:getPassword",
    {
      branch: args.branch,
      database: args.database,
      id: args.id,
      organization: args.organization,
      readOnlyRegionId: args.readOnlyRegionId,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getPassword.
 */
export interface GetPasswordOutputArgs {
  branch: pulumi.Input<string>;
  database: pulumi.Input<string>;
  id: pulumi.Input<string>;
  organization: pulumi.Input<string>;
  readOnlyRegionId?: pulumi.Input<string>;
}
