// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getUser(opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    "planetscale:index/getUser:getUser",
    {},
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
  readonly avatarUrl: string;
  readonly createdAt: string;
  readonly defaultOrganization: outputs.GetUserDefaultOrganization;
  readonly directoryManaged: boolean;
  readonly displayName: string;
  readonly email: string;
  readonly emailVerified: boolean;
  readonly id: string;
  readonly managed: boolean;
  readonly name: string;
  readonly sso: boolean;
  readonly twoFactorAuthConfigured: boolean;
  readonly updatedAt: string;
}
export function getUserOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUserResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    "planetscale:index/getUser:getUser",
    {},
    opts,
    utilities.getPackage(),
  );
}
