// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Password extends pulumi.CustomResource {
  /**
   * Get an existing Password resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: PasswordState,
    opts?: pulumi.CustomResourceOptions,
  ): Password {
    return new Password(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = "planetscale:index/password:Password";

  /**
   * Returns true if the given object is an instance of Password.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Password {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj.__pulumiType === Password.__pulumiType;
  }

  /**
   * The host URL for the password.
   */
  declare public readonly /*out*/ accessHostUrl: pulumi.Output<string>;
  /**
   * The actor that created this branch.
   */
  declare public readonly /*out*/ actor: pulumi.Output<outputs.PasswordActor>;
  /**
   * The branch this password belongs to.
   */
  declare public readonly branch: pulumi.Output<string>;
  /**
   * List of IP addresses or CIDR ranges that can use this password. Individual IPs must still contain a prefix, eg: 127.0.0.1/32
   */
  declare public readonly cidrs: pulumi.Output<string[] | undefined>;
  /**
   * When the password was created.
   */
  declare public readonly /*out*/ createdAt: pulumi.Output<string>;
  /**
   * The database this branch password belongs to.
   */
  declare public readonly database: pulumi.Output<string>;
  /**
   * The branch this password is allowed to access.
   */
  declare public readonly /*out*/ databaseBranch: pulumi.Output<outputs.PasswordDatabaseBranch>;
  /**
   * When the password was deleted.
   */
  declare public readonly /*out*/ deletedAt: pulumi.Output<string>;
  /**
   * When the password will expire.
   */
  declare public readonly /*out*/ expiresAt: pulumi.Output<string>;
  /**
   * The display name for the password.
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * The organization this database branch password belongs to.
   */
  declare public readonly organization: pulumi.Output<string>;
  /**
   * The plaintext password, only available if the password was created by this provider.
   */
  declare public readonly /*out*/ plaintext: pulumi.Output<string>;
  /**
   * The region in which this password can be used.
   */
  declare public readonly /*out*/ region: pulumi.Output<outputs.PasswordRegion>;
  /**
   * Whether or not the password can be renewed.
   */
  declare public readonly /*out*/ renewable: pulumi.Output<boolean>;
  /**
   * When true, all queries from this password will be read-only and directed to a replica. Requires role to be set to reader.
   */
  declare public readonly replica: pulumi.Output<boolean>;
  /**
   * The role for the password.
   */
  declare public readonly role: pulumi.Output<string>;
  /**
   * Time to live (in seconds) for the password. The password will be invalid and unrenewable when TTL has passed.
   */
  declare public readonly ttlSeconds: pulumi.Output<number>;
  /**
   * The username for the password.
   */
  declare public readonly /*out*/ username: pulumi.Output<string>;

  /**
   * Create a Password resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: PasswordArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: PasswordArgs | PasswordState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as PasswordState | undefined;
      resourceInputs.accessHostUrl = state?.accessHostUrl;
      resourceInputs.actor = state?.actor;
      resourceInputs.branch = state?.branch;
      resourceInputs.cidrs = state?.cidrs;
      resourceInputs.createdAt = state?.createdAt;
      resourceInputs.database = state?.database;
      resourceInputs.databaseBranch = state?.databaseBranch;
      resourceInputs.deletedAt = state?.deletedAt;
      resourceInputs.expiresAt = state?.expiresAt;
      resourceInputs.name = state?.name;
      resourceInputs.organization = state?.organization;
      resourceInputs.plaintext = state?.plaintext;
      resourceInputs.region = state?.region;
      resourceInputs.renewable = state?.renewable;
      resourceInputs.replica = state?.replica;
      resourceInputs.role = state?.role;
      resourceInputs.ttlSeconds = state?.ttlSeconds;
      resourceInputs.username = state?.username;
    } else {
      const args = argsOrState as PasswordArgs | undefined;
      if (args?.branch === undefined && !opts.urn) {
        throw new Error("Missing required property 'branch'");
      }
      if (args?.database === undefined && !opts.urn) {
        throw new Error("Missing required property 'database'");
      }
      if (args?.organization === undefined && !opts.urn) {
        throw new Error("Missing required property 'organization'");
      }
      resourceInputs.branch = args?.branch;
      resourceInputs.cidrs = args?.cidrs;
      resourceInputs.database = args?.database;
      resourceInputs.name = args?.name;
      resourceInputs.organization = args?.organization;
      resourceInputs.replica = args?.replica;
      resourceInputs.role = args?.role;
      resourceInputs.ttlSeconds = args?.ttlSeconds;
      resourceInputs.accessHostUrl = undefined /*out*/;
      resourceInputs.actor = undefined /*out*/;
      resourceInputs.createdAt = undefined /*out*/;
      resourceInputs.databaseBranch = undefined /*out*/;
      resourceInputs.deletedAt = undefined /*out*/;
      resourceInputs.expiresAt = undefined /*out*/;
      resourceInputs.plaintext = undefined /*out*/;
      resourceInputs.region = undefined /*out*/;
      resourceInputs.renewable = undefined /*out*/;
      resourceInputs.username = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ["plaintext"] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      Password.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Password resources.
 */
export interface PasswordState {
  /**
   * The host URL for the password.
   */
  accessHostUrl?: pulumi.Input<string>;
  /**
   * The actor that created this branch.
   */
  actor?: pulumi.Input<inputs.PasswordActor>;
  /**
   * The branch this password belongs to.
   */
  branch?: pulumi.Input<string>;
  /**
   * List of IP addresses or CIDR ranges that can use this password. Individual IPs must still contain a prefix, eg: 127.0.0.1/32
   */
  cidrs?: pulumi.Input<pulumi.Input<string>[]>;
  /**
   * When the password was created.
   */
  createdAt?: pulumi.Input<string>;
  /**
   * The database this branch password belongs to.
   */
  database?: pulumi.Input<string>;
  /**
   * The branch this password is allowed to access.
   */
  databaseBranch?: pulumi.Input<inputs.PasswordDatabaseBranch>;
  /**
   * When the password was deleted.
   */
  deletedAt?: pulumi.Input<string>;
  /**
   * When the password will expire.
   */
  expiresAt?: pulumi.Input<string>;
  /**
   * The display name for the password.
   */
  name?: pulumi.Input<string>;
  /**
   * The organization this database branch password belongs to.
   */
  organization?: pulumi.Input<string>;
  /**
   * The plaintext password, only available if the password was created by this provider.
   */
  plaintext?: pulumi.Input<string>;
  /**
   * The region in which this password can be used.
   */
  region?: pulumi.Input<inputs.PasswordRegion>;
  /**
   * Whether or not the password can be renewed.
   */
  renewable?: pulumi.Input<boolean>;
  /**
   * When true, all queries from this password will be read-only and directed to a replica. Requires role to be set to reader.
   */
  replica?: pulumi.Input<boolean>;
  /**
   * The role for the password.
   */
  role?: pulumi.Input<string>;
  /**
   * Time to live (in seconds) for the password. The password will be invalid and unrenewable when TTL has passed.
   */
  ttlSeconds?: pulumi.Input<number>;
  /**
   * The username for the password.
   */
  username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Password resource.
 */
export interface PasswordArgs {
  /**
   * The branch this password belongs to.
   */
  branch: pulumi.Input<string>;
  /**
   * List of IP addresses or CIDR ranges that can use this password. Individual IPs must still contain a prefix, eg: 127.0.0.1/32
   */
  cidrs?: pulumi.Input<pulumi.Input<string>[]>;
  /**
   * The database this branch password belongs to.
   */
  database: pulumi.Input<string>;
  /**
   * The display name for the password.
   */
  name?: pulumi.Input<string>;
  /**
   * The organization this database branch password belongs to.
   */
  organization: pulumi.Input<string>;
  /**
   * When true, all queries from this password will be read-only and directed to a replica. Requires role to be set to reader.
   */
  replica?: pulumi.Input<boolean>;
  /**
   * The role for the password.
   */
  role?: pulumi.Input<string>;
  /**
   * Time to live (in seconds) for the password. The password will be invalid and unrenewable when TTL has passed.
   */
  ttlSeconds?: pulumi.Input<number>;
}
