// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the planetscale package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
  /** @internal */
  public static readonly __pulumiType = "planetscale";

  /**
   * Returns true if the given object is an instance of Provider.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Provider {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj.__pulumiType === `pulumi:providers:${Provider.__pulumiType}`;
  }

  /**
   * Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_ID`. Mutually exclusive with <span pulumi-lang-nodejs="`serviceTokenId`" pulumi-lang-dotnet="`ServiceTokenId`" pulumi-lang-go="`serviceTokenId`" pulumi-lang-python="`service_token_id`" pulumi-lang-yaml="`serviceTokenId`" pulumi-lang-java="`serviceTokenId`">`service_token_id`</span> and <span pulumi-lang-nodejs="`serviceToken`" pulumi-lang-dotnet="`ServiceToken`" pulumi-lang-go="`serviceToken`" pulumi-lang-python="`service_token`" pulumi-lang-yaml="`serviceToken`" pulumi-lang-java="`serviceToken`">`service_token`</span>.
   */
  declare public readonly accessToken: pulumi.Output<string | undefined>;
  /**
   * If set, points the API client to a different endpoint than `https://api.planetscale.com/v1`.
   */
  declare public readonly endpoint: pulumi.Output<string | undefined>;
  /**
   * Value of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>.
   */
  declare public readonly serviceToken: pulumi.Output<string | undefined>;
  /**
   * ID of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_ID`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>.
   */
  declare public readonly serviceTokenId: pulumi.Output<string | undefined>;
  /**
   * Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>. (Deprecated, use <span pulumi-lang-nodejs="`serviceTokenId`" pulumi-lang-dotnet="`ServiceTokenId`" pulumi-lang-go="`serviceTokenId`" pulumi-lang-python="`service_token_id`" pulumi-lang-yaml="`serviceTokenId`" pulumi-lang-java="`serviceTokenId`">`service_token_id`</span> instead)
   *
   * @deprecated Deprecated
   */
  declare public readonly serviceTokenName: pulumi.Output<string | undefined>;

  /**
   * Create a Provider resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
    const resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    resourceInputs.accessToken = args?.accessToken ? pulumi.secret(args.accessToken) : undefined;
    resourceInputs.endpoint = args?.endpoint;
    resourceInputs.serviceToken = args?.serviceToken ? pulumi.secret(args.serviceToken) : undefined;
    resourceInputs.serviceTokenId = args?.serviceTokenId;
    resourceInputs.serviceTokenName = args?.serviceTokenName;
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = {
      additionalSecretOutputs: ["accessToken", "serviceToken"],
    };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      Provider.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }

  /**
   * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
   */
  terraformConfig(): pulumi.Output<{ [key: string]: any }> {
    const result: pulumi.Output<Provider.TerraformConfigResult> = pulumi.runtime.call(
      "pulumi:providers:planetscale/terraformConfig",
      {
        __self__: this,
      },
      this,
      utilities.getPackage(),
    );
    return result.result;
  }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
  /**
   * Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_ID`. Mutually exclusive with <span pulumi-lang-nodejs="`serviceTokenId`" pulumi-lang-dotnet="`ServiceTokenId`" pulumi-lang-go="`serviceTokenId`" pulumi-lang-python="`service_token_id`" pulumi-lang-yaml="`serviceTokenId`" pulumi-lang-java="`serviceTokenId`">`service_token_id`</span> and <span pulumi-lang-nodejs="`serviceToken`" pulumi-lang-dotnet="`ServiceToken`" pulumi-lang-go="`serviceToken`" pulumi-lang-python="`service_token`" pulumi-lang-yaml="`serviceToken`" pulumi-lang-java="`serviceToken`">`service_token`</span>.
   */
  accessToken?: pulumi.Input<string>;
  /**
   * If set, points the API client to a different endpoint than `https://api.planetscale.com/v1`.
   */
  endpoint?: pulumi.Input<string>;
  /**
   * Value of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>.
   */
  serviceToken?: pulumi.Input<string>;
  /**
   * ID of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_ID`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>.
   */
  serviceTokenId?: pulumi.Input<string>;
  /**
   * Name of the service token to use. Alternatively, use `PLANETSCALE_SERVICE_TOKEN_NAME`. Mutually exclusive with <span pulumi-lang-nodejs="`accessToken`" pulumi-lang-dotnet="`AccessToken`" pulumi-lang-go="`accessToken`" pulumi-lang-python="`access_token`" pulumi-lang-yaml="`accessToken`" pulumi-lang-java="`accessToken`">`access_token`</span>. (Deprecated, use <span pulumi-lang-nodejs="`serviceTokenId`" pulumi-lang-dotnet="`ServiceTokenId`" pulumi-lang-go="`serviceTokenId`" pulumi-lang-python="`service_token_id`" pulumi-lang-yaml="`serviceTokenId`" pulumi-lang-java="`serviceTokenId`">`service_token_id`</span> instead)
   *
   * @deprecated Deprecated
   */
  serviceTokenName?: pulumi.Input<string>;
}

export namespace Provider {
  /**
   * The results of the Provider.terraformConfig method.
   */
  export interface TerraformConfigResult {
    readonly result: { [key: string]: any };
  }
}
